version: 2.1

executors:
  deploy-defaults:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /dockerapp
jobs:
  build:
    executor: deploy-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
  test-docker:
    executor: deploy-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
  upload-docker-artifact:
    executor: deploy-defaults
    steps:
      - run:
          name: Upload Docker
          command: |
            echo "Uploading Docker"
  deploy-docker:
    executor: deploy-defaults
    steps:
      - run:
          name: Deploy Docker
          command: |
            echo "Deploying Docker"
  result-docker:
    executor: deploy-defaults
    steps:
      - run:
          name: Result Docker
          command: |
            echo "Docker Result"

workflows:
  version: 2

  pipeline:
    jobs:
      - build
      - test-docker:
          requires:
            - build
      - deploy-docker:
          requires:
          - test-docker
      - result-docker:
          requires:
            - deploy-docker
            - test-docker

